### ISSUE TITLE
SE-SENAO Bug #2

### ISSUE THREAD

**Issue by inesbruna** [inesbruna/visualgcompilator#2]
**Sintax:** 
se ( a = 3 ) e (xou (i > 5)) entao

**Error Message:**
Resultado: Erro: Palavra não esperada "XOU", Token Esperado: COMPARACAO, 
Pilha: "['COMANDOS', 'PARA_COMANDOS', 'SE_COMANDOS', 'MAISCOMPARACAO', 'FECHAPARENTESES']"

**Comment by FernandoFelixNunesTeixeira** [comment]
Acho que esse xou nesse caso pode não ser aceito mesmo, tem outras coisas mais importantes para corrigir

**Comment by inesbruna** [comment]
> Acho que esse xou nesse caso pode não ser aceito mesmo, tem outras coisas mais importantes para corrigir

Perdão eu coloquei errado, vou corrigir

**Comment by FernandoFelixNunesTeixeira** [comment]
Ok
